// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/update-app-state": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/projects": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/update-app-state" | "/blog/:slug" | "/projects" | "/about" | "/blogs" | "/*";
  };
  "routes/api.update-app-state.ts": {
    id: "routes/api.update-app-state";
    page: "/api/update-app-state";
  };
  "routes/_web/route.tsx": {
    id: "routes/_web";
    page: "/blog/:slug" | "/projects" | "/" | "/about" | "/blogs" | "/*";
  };
  "routes/_web.blog.$slug/route.tsx": {
    id: "routes/_web.blog.$slug";
    page: "/blog/:slug";
  };
  "routes/_web.projects/route.tsx": {
    id: "routes/_web.projects";
    page: "/projects";
  };
  "routes/_web._index/route.tsx": {
    id: "routes/_web._index";
    page: "/";
  };
  "routes/_web.about/route.tsx": {
    id: "routes/_web.about";
    page: "/about";
  };
  "routes/_web.blogs/route.tsx": {
    id: "routes/_web.blogs";
    page: "/blogs";
  };
  "routes/_web.$.tsx": {
    id: "routes/_web.$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.update-app-state": typeof import("./app/routes/api.update-app-state.ts");
  "routes/_web": typeof import("./app/routes/_web/route.tsx");
  "routes/_web.blog.$slug": typeof import("./app/routes/_web.blog.$slug/route.tsx");
  "routes/_web.projects": typeof import("./app/routes/_web.projects/route.tsx");
  "routes/_web._index": typeof import("./app/routes/_web._index/route.tsx");
  "routes/_web.about": typeof import("./app/routes/_web.about/route.tsx");
  "routes/_web.blogs": typeof import("./app/routes/_web.blogs/route.tsx");
  "routes/_web.$": typeof import("./app/routes/_web.$.tsx");
};