// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*";
  };
  "routes/_web/route.tsx": {
    id: "routes/_web";
    page: "/" | "/*";
  };
  "routes/_web._index/route.tsx": {
    id: "routes/_web._index";
    page: "/";
  };
  "routes/_web.$.tsx": {
    id: "routes/_web.$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_web": typeof import("./app/routes/_web/route.tsx");
  "routes/_web._index": typeof import("./app/routes/_web._index/route.tsx");
  "routes/_web.$": typeof import("./app/routes/_web.$.tsx");
};