// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/update-app-state": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/project/mediapipe-webworker": {
    params: {};
  };
  "/project-blog": {
    params: {};
  };
  "/project-blog/clean-jsdoc-theme": {
    params: {};
  };
  "/project-blog/ersilia-reinvent4": {
    params: {};
  };
  "/project-blog/outspeed-js": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/projects": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/update-app-state" | "/sitemap.xml" | "/project/mediapipe-webworker" | "/project-blog" | "/project-blog/clean-jsdoc-theme" | "/project-blog/ersilia-reinvent4" | "/project-blog/outspeed-js" | "/blog/:slug" | "/projects" | "/about" | "/blogs" | "/*";
  };
  "routes/api.update-app-state.ts": {
    id: "routes/api.update-app-state";
    page: "/api/update-app-state";
  };
  "routes/[sitemap.xml].ts": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/_web/route.tsx": {
    id: "routes/_web";
    page: "/project/mediapipe-webworker" | "/project-blog" | "/project-blog/clean-jsdoc-theme" | "/project-blog/ersilia-reinvent4" | "/project-blog/outspeed-js" | "/blog/:slug" | "/projects" | "/" | "/about" | "/blogs" | "/*";
  };
  "routes/_web.project.mediapipe-webworker/route.tsx": {
    id: "routes/_web.project.mediapipe-webworker";
    page: "/project/mediapipe-webworker";
  };
  "routes/_web.project-blog/route.tsx": {
    id: "routes/_web.project-blog";
    page: "/project-blog" | "/project-blog/clean-jsdoc-theme" | "/project-blog/ersilia-reinvent4" | "/project-blog/outspeed-js";
  };
  "routes/_web.project-blog.clean-jsdoc-theme/route.tsx": {
    id: "routes/_web.project-blog.clean-jsdoc-theme";
    page: "/project-blog/clean-jsdoc-theme";
  };
  "routes/_web.project-blog.ersilia-reinvent4/route.tsx": {
    id: "routes/_web.project-blog.ersilia-reinvent4";
    page: "/project-blog/ersilia-reinvent4";
  };
  "routes/_web.project-blog.outspeed-js/route.tsx": {
    id: "routes/_web.project-blog.outspeed-js";
    page: "/project-blog/outspeed-js";
  };
  "routes/_web.blog.$slug/route.tsx": {
    id: "routes/_web.blog.$slug";
    page: "/blog/:slug";
  };
  "routes/_web.projects/route.tsx": {
    id: "routes/_web.projects";
    page: "/projects";
  };
  "routes/_web._index/route.tsx": {
    id: "routes/_web._index";
    page: "/";
  };
  "routes/_web.about/route.tsx": {
    id: "routes/_web.about";
    page: "/about";
  };
  "routes/_web.blogs/route.tsx": {
    id: "routes/_web.blogs";
    page: "/blogs";
  };
  "routes/_web.$.tsx": {
    id: "routes/_web.$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.update-app-state": typeof import("./app/routes/api.update-app-state.ts");
  "routes/[sitemap.xml]": typeof import("./app/routes/[sitemap.xml].ts");
  "routes/_web": typeof import("./app/routes/_web/route.tsx");
  "routes/_web.project.mediapipe-webworker": typeof import("./app/routes/_web.project.mediapipe-webworker/route.tsx");
  "routes/_web.project-blog": typeof import("./app/routes/_web.project-blog/route.tsx");
  "routes/_web.project-blog.clean-jsdoc-theme": typeof import("./app/routes/_web.project-blog.clean-jsdoc-theme/route.tsx");
  "routes/_web.project-blog.ersilia-reinvent4": typeof import("./app/routes/_web.project-blog.ersilia-reinvent4/route.tsx");
  "routes/_web.project-blog.outspeed-js": typeof import("./app/routes/_web.project-blog.outspeed-js/route.tsx");
  "routes/_web.blog.$slug": typeof import("./app/routes/_web.blog.$slug/route.tsx");
  "routes/_web.projects": typeof import("./app/routes/_web.projects/route.tsx");
  "routes/_web._index": typeof import("./app/routes/_web._index/route.tsx");
  "routes/_web.about": typeof import("./app/routes/_web.about/route.tsx");
  "routes/_web.blogs": typeof import("./app/routes/_web.blogs/route.tsx");
  "routes/_web.$": typeof import("./app/routes/_web.$.tsx");
};