const home = {
  ankit_kumar: "Ankit Kumar",
  intro:
    "Hey 👋, so glad you're here.<1></1><1></1>A little about me, I'm a <0>Co-Founder</0>, <0>Software Engineer</0>, <0>UI/UX Designer</0>, and <0>Mentor</0>—crafting  tools people enjoy, writing thoughtful, maintainable code, and helping others grow with me.<1></1><1></1>And most importantly, I'm rooted in Nalanda, Bihar (India).",
  about_me: `My frontend journey started after co-founding Asaan, a startup focused on democratizing digital platforms to codify business processes. Due to limited resources, I took end-to-end ownership of many projects and was involved in the complete lifecycle of each project. My work included designing and implementing interfaces and understanding user needs through individual interviews to create effective solutions.<0></0><0></0>Alongside my professional work, I maintain clean-jsdoc-theme (58,000 weekly downloads) and contribute to open-source projects like Ersilia, where I integrated a generative AI model for drug discovery, gaining Python and Docker experience. My frontend journey started after co-founding Asaan, a startup focused on democratizing digital platforms to codify business processes. Due to limited resources, I took end-to-end ownership of many projects and was involved in the complete lifecycle of each project. My work included designing and implementing interfaces and understanding user needs through individual interviews to create effective solutions.<0></0><0></0>Alongside my professional work, I maintain clean-jsdoc-theme (58,000 weekly downloads) and contribute to open-source projects like Ersilia, where I integrated a generative AI model for drug discovery, gaining Python and Docker experience.My frontend journey started after co-founding Asaan, a startup focused on democratizing digital platforms to codify business processes. Due to limited resources, I took end-to-end ownership of many projects and was involved in the complete lifecycle of each project. My work included designing and implementing interfaces and understanding user needs through individual interviews to create effective solutions.<0></0><0></0>Alongside my professional work, I maintain clean-jsdoc-theme (58,000 weekly downloads) and contribute to open-source projects like Ersilia, where I integrated a generative AI model for drug discovery, gaining Python and Docker experience.My frontend journey started after co-founding Asaan, a startup focused on democratizing digital platforms to codify business processes. Due to limited resources, I took end-to-end ownership of many projects and was involved in the complete lifecycle of each project. My work included designing and implementing interfaces and understanding user needs through individual interviews to create effective solutions.<0></0><0></0>Alongside my professional work, I maintain clean-jsdoc-theme (58,000 weekly downloads) and contribute to open-source projects like Ersilia, where I integrated a generative AI model for drug discovery, gaining Python and Docker experience.`,
};

export default home;
export type HomeTranslation = typeof home;
